version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo 'Hello World!' > hello.txt

artifacts:
  name: greetings
  files:
    - '**/*.txt'
  discard-paths: yes
