version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo 'Hello World!' > hello.txt
      - wget https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
      - unzip terraform_0.12.21_linux_amd64.zip
      - rm -f terraform_0.12.21_linux_amd64.zip
      - mv terraform /usr/local/bin
      - ./deploy-app-infra.sh

artifacts:
  name: greetings
  files:
    - '**/*.txt'
  discard-paths: yes
